/**
 * Myworkout API
 * Documentation for Myworkout API.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface Team {
    /**
     * ID of the team
     */
    id?: number;
    /**
     * The name of the team
     */
    name?: string;
}
