/**
 * Myworkout API
 * Documentation for Myworkout API.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TeamMember {
    /**
     * team member id
     */
    id?: number;
    /**
     * team member name
     */
    name?: string;
    role?: TeamMember.RoleEnum;
}
export declare namespace TeamMember {
    type RoleEnum = 'member' | 'captain';
    const RoleEnum: {
        Member: RoleEnum;
        Captain: RoleEnum;
    };
}
